openapi: 3.0.3
info:
  title: Image Compare
  version: 0.1.0
  description: Backend for image compare, a website for facilitating citizen science projects relating to imaging and mathematics.
  contact:
    email: lily.mosquitoes@gmail.com

servers:
  - url: http://127.0.0.1:8000

tags:
  - name: Healthcheck
  - name: User
  - name: Comparison
  - name: Vote
  - name: Image
  - name: Admin

paths:
  /api/healthcheck:
    get:
      summary: perform healthcheck
      description: Returns OK, endpoint for CI/CD
      operationId: get_healthcheck
      tags:
        - Healthcheck
      responses:
        '200':
          description: Server is up and responding
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultProperties'
  /api/user/{id}:
    get:
      summary: get a user by id
      description: Returns the information of the user by ID
      operationId: get_user
      tags:
        - User
      parameters:
        - name: id
          in: path
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: User information returned
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/DefaultProperties'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/User'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/DefaultProperties'
                - type: object
                  properties:
                    error:
                      type: string
                      example: 'ID must be UUID'
        '404':
          $ref: '#/components/responses/404_NotFound'
        '500':
          $ref: '#/components/responses/500_InternalServerError'
  /api/user:
    post:
      summary: create a new user
      description: Creates a new user in the database
      operationId: post_user
      tags:
        - User
      responses:
        '201':
          description: User Created
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/DefaultProperties'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/User'
        '500':
          $ref: '#/components/responses/500_InternalServerError'
  /api/user/{id}/comparison:
    get:
      summary: get a new comparison for the user
      description: Returns a comparison object the user has not voted on yet
      operationId: get_comparison
      tags:
        - Comparison
      parameters:
        - name: id
          in: path
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: Images returned for comparison; currently always 2
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/DefaultProperties'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/Comparison'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/DefaultProperties'
                - type: object
                  properties:
                    error:
                      type: string
                      example: 'ID must be UUID'
        '404':
          $ref: '#/components/responses/404_NotFound'
        '503':
          $ref: '#/components/responses/503_ServiceUnavailable'
        '500':
          $ref: '#/components/responses/500_InternalServerError'
  /api/vote:
    post:
      summary: vote on a comparison, as a user
      description: Creates a new vote from the user for a comparison
      operationId: post_vote
      tags:
        - Vote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoteForm'
      responses:
        '201':
          description: Vote Created
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/DefaultProperties'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/Vote'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/DefaultProperties'
                - type: object
                  properties:
                    error:
                      type: string
                      example: '`user` with requested id not found'
        '500':
          $ref: '#/components/responses/500_InternalServerError'
  /static/images/{filename}:
    get:
      summary: get an image with a filename
      description: Returns an image
      operationId: get_image
      tags:
        - Image
      parameters:
        - name: filename
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Image returned
          content:
            image/png:
              schema:
                type: string
                format: binary
        '404':
          $ref: '#/components/responses/404_NotFound'
  /api/admin/comparison:
    post:
      summary: generate comparisons in database from the static folder
      description: Returns all comparisons generated. The comparisons are based on the images currently in the static folder and comparsiosns between two images are only done for images under the same subfolder's root.
      operationId: post_admin_comparison
      tags:
        - Admin
        - Comparison
      security:
        - BearerAuth: []
      responses:
        '201':
          description: Comparisons created
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/DefaultProperties'
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/Comparison'
        '401':
          $ref: '#/components/responses/401_Unauthorized'
        '500':
          $ref: '#/components/responses/500_InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  headers:
    Location:
      description: Location of the created resource
      schema:
        type: string
        format: uri
        example: 'http://localhost:3000/api/path'
    Retry-After:
      description: Estimated downtime, in seconds
      schema:
        type: integer
        example: 36000
  responses:
    401_Unauthorized:
      description: Unauthorized
      headers:
        WWW-Authenticate:
          schema:
            type: string
            example: 'Bearer'
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DefaultProperties'
              - type: object
                properties:
                  error:
                    type: string
                    example: 'Unauthorized'
    404_NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DefaultProperties'
              - type: object
                properties:
                  error:
                    type: string
                    example: 'Resource not found'
    500_InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DefaultProperties'
              - type: object
                properties:
                  error:
                    type: string
                    example: 'The server encountered an error; please contact the server administrator'
    503_ServiceUnavailable:
      description: Service Unavailable
      headers:
        Retry-After:
          $ref: '#/components/headers/Retry-After'
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/DefaultProperties'
              - type: object
                properties:
                  error:
                    type: string
                    example: 'This service is unavailable; please try later'
  schemas:
    DefaultProperties:
      type: object
      properties:
        request_id:
          type: integer
        timestamp:
          type: string
          format: date-time
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        votes:
          type: integer
        average_lambda:
          type: number
          format: float
    Comparison:
      type: object
      properties:
        id:
          type: string
          format: uuid
        dirname:
          type: string
          example: 'birds'
        images:
          type: array
          items:
            type: string
            format: uri
            example: '/static/images/birds/image%20A.png'
          example: ['/static/images/birds/image%20A.png', '/static/images/birds/imageB.png']
    VoteForm:
      type: object
      properties:
        comparison_id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        image:
          type: string
          format: uri
          example: '/static/images/birds/image%20A.png'
    Vote:
      allOf:
      - type: object
        properties:
          id:
            type: integer
            format: int64
      - $ref: '#/components/schemas/VoteForm'
      - type: object
        properties:
          created_at:
            type: string
            format: date-time
          ip_addr:
            type: string
            format: ipv4
